# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-06-10 03:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('diy', django.db.models.manager.Manager()),
            ],
        ),
    ]
