# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200610_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('zuozhe', models.CharField(max_length=100, verbose_name='作者')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
            ],
        ),
    ]
