# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-23 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, default=30, null=True, verbose_name='年龄')),
                ('passwd', models.CharField(default='', max_length=100, null=True, verbose_name='密码')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userInformation',
            },
        ),
    ]
