# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authpermis', '0002_auto_20200720_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名字')),
                ('type', models.IntegerField(choices=[(1, '普通用户'), (2, '老师')], verbose_name='用户类型')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authpermis.User'),
        ),
    ]
