# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authpermis', '0003_auto_20200720_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authpermis.User'),
        ),
    ]
